#!/bin/bash
# usage: deploy-kubevirt (minikube|minishift|oc_cluster) $KUBEVIRT_VERSION

set -e

source $(dirname $(realpath $0))/defaults

_kubernetes() {
  local VER=$1

  kubectl create configmap -n kubevirt kubevirt-config --from-literal debug.useEmulation=true || :
  kubectl apply -f https://github.com/kubevirt/kubevirt/releases/download/$VER/kubevirt.yaml ;
}

_origin() {
  local VER=$1

  oc login -u system:admin

  _kubernetes $VER

  oc adm policy add-scc-to-user privileged -n kubevirt -z kubevirt-privileged
  oc adm policy add-scc-to-user privileged -n kubevirt -z kubevirt-controller
  oc adm policy add-scc-to-user privileged -n kubevirt -z kubevirt-apiserver
}

_${CDIST_ON[${1:-$DEFAULT_PLATFORM}]} ${2:-$DEFAULT_KUBEVIRT_VER}

bash ci/wait-pods-ok

# Give kvm some time to be announced
sleep 12

kubectl describe nodes
