#!/bin/bash
# usage: deploy-kubevirt (kubernetes|origin) $KUBEVIRT_VERSION

set -e

_kubernetes() {
  local VER=$1

  kubectl create configmap -n kube-system kubevirt-config --from-literal debug.useEmulation=true || :
  kubectl apply -f https://github.com/kubevirt/kubevirt/releases/download/$VER/kubevirt.yaml ;
}

_origin() {
  local VER=$1

  _kubernetes $VER

  oc adm policy add-scc-to-user privileged -n kube-system -z kubevirt-privileged
  oc adm policy add-scc-to-user privileged -n kube-system -z kubevirt-controller
  oc adm policy add-scc-to-user privileged -n kube-system -z kubevirt-apiserver
}

_$1 $2

timeout 2m ci/wait-pods-ok
