#!/bin/bash
# usage: deploy-kubevirt (minikube|minishift|oc_cluster) $KUBEVIRT_VERSION

set -e

source ci/defaults

_kubernetes() {
  local VER=$1

  kubectl create configmap -n kube-system kubevirt-config --from-literal debug.useEmulation=true || :
  kubectl apply -f https://github.com/kubevirt/kubevirt/releases/download/v$VER/kubevirt.yaml ;
}

_origin() {
  local VER=$1

  _kubernetes $VER

  oc adm policy add-scc-to-user privileged -n kube-system -z kubevirt-privileged
  oc adm policy add-scc-to-user privileged -n kube-system -z kubevirt-controller
  oc adm policy add-scc-to-user privileged -n kube-system -z kubevirt-apiserver
}

_${CDIST_ON[${1:-$DEFAULT_PLATFORM}]} ${2:-$DEFAULT_KUBEVIRT_VER}

timeout 5m ci/wait-pods-ok

# Give kvm some time to be announced
sleep 12

kubectl describe nodes
