#!/bin/bash
# usage: prepare-host (minikube|oc_cluster) $VERSION

set -e

_minikube() {
  local CVER=$1

  curl -Lo kubectl \
    https://storage.googleapis.com/kubernetes-release/release/v$CVER/bin/linux/amd64/kubectl

  sudo install -m a+x kubectl /usr/local/bin

  curl -L \
    https://github.com/kubernetes-incubator/cri-tools/releases/download/v1.11.1/crictl-v1.11.1-linux-amd64.tar.gz \
    | tar xz crictl

  sudo install -m a+x crictl /usr/local/bin

  curl -Lo minikube \
    https://storage.googleapis.com/minikube/releases/v0.28.2/minikube-linux-amd64

  sudo install -m a+x minikube /usr/local/bin
}

__install_oc() {
  curl -L \
    https://github.com/openshift/origin/releases/download/v$CVER/openshift-origin-client-tools-v3.10.0-dd10d17-linux-64bit.tar.gz \
    | tar xz --strip-components=1 openshift-origin-client-tools-v3.10.0-dd10d17-linux-64bit/oc

  sudo install -m a+x oc /usr/local/bin
  # For compatibility
  sudo ln -sf /usr/local/bin/oc /usr/local/bin/kubectl
}

_oc_cluster() {
  local CVER=$1

  sudo sed -i 's%DOCKER_OPTS=\"%DOCKER_OPTS=\"--insecure-registry 172.30.0.0/16 %' /etc/default/docker
  sudo systemctl restart docker

  __install_oc
}

_minishift() {
  curl -L \
    https://github.com/minishift/minishift/releases/download/v1.23.0/minishift-1.23.0-linux-amd64.tgz \
    | tar xz --strip-components=1 minishift-1.23.0-linux-amd64/minishift

  sudo install -m a+x minishift /usr/local/bin

  USSH=$HOME/.ssh
  mkdir -p $USSH
  ssh-keygen -t rsa -N '' -f $USSH/ci_id_rsa
  echo 'Host localhost' >> $USSH/config
  echo '  StrictHostKeyChecking no' >> $USSH/config
  chmod g-rw,o-rw $USSH/* $USSH

  sudo mkdir -p /root/.ssh
  sudo sh -c "cat $USSH/ci_id_rsa.pub >> /root/.ssh/authorized_keys"
  sudo sh -c "chmod g-rw,o-rw /root/.ssh /root/.ssh/*"

  __install_oc
}

_$1 $2
