#!/bin/bash
# usage: start-cluster (minikube|oc_cluster) $VERSION

set -e

_minikube() {
  local CVER=$1

  export MINIKUBE_WANTUPDATENOTIFICATION=false
  export MINIKUBE_WANTREPORTERRORPROMPT=false
  export CHANGE_MINIKUBE_NONE_USER=true

  export MINIKUBE_HOME=$HOME
  mkdir -p $HOME/.kube
  touch $HOME/.kube/config
  export KUBECONFIG=$HOME/.kube/config

  sudo -E minikube start \
    --vm-driver=none \
    --kubernetes-version=v$CVER

  minikube update-context
}

_oc_cluster() {
  local CVER=$1

  oc version
  oc cluster up --skip-registry-check --enable=-router,-sample-templates

  oc login -u system:admin
}

_minishift() {
  local CVER=$1

  minishift version
  minishift start \
    --vm-driver=generic \
    --remote-ipaddress 127.0.0.1 \
    --remote-ssh-user root \
    --remote-ssh-key $HOME/.ssh/ci_id_rsa \
    --openshift-version=v$CVER

  oc login -u system:admin
}

_$1 $2

timeout 1m bash ci/wait-pods-ok
