#!/usr/bin/bash

#
# If this file is empty, then no workarounds for any are required
#
# If this file is NOT empty, then some platform might require a workaround
#

# Add a workaround here
# Prefix it with for_, i.e.: for_minishift_dp_issue()

_$@
